export const COMPANY_INFO = {
  name: 'Shree Ji Taxi Service',
  nameHindi: 'श्री जी टैक्सी सर्विस',
  owner: 'Vijay Yadav',
  ownerHindi: 'विजय यादव',
  phone1: '9953066750',
  phone2: '9205272745',
  whatsapp: '9953066750',
  email: 'shreejitaxi@gmail.com',
  address: 'Swarg Ashram Colony, GTB Nagar, Mukherjee Nagar, New Delhi - 110009',
  addressHindi: 'स्वर्ग आश्रम कॉलोनी, जीटीबी नगर, मुखर्जी नगर, नई दिल्ली - 110009',
  establishedYear: 2010,
};

export const FLEET = [
  {
    id: 'ertiga',
    name: 'Maruti Ertiga',
    nameHindi: 'मारुति अर्टिगा',
    capacity: 6,
    luggage: 3,
    type: 'MPV',
    image: '/images/fleet/ertiga.jpg',
    features: ['AC', 'Music System', 'Spacious', 'Mobile Charger', 'Luggage Space'],
  },
  {
    id: 'dzire',
    name: 'Maruti Dzire',
    nameHindi: 'मारुति डिज़ायर',
    capacity: 4,
    luggage: 2,
    type: 'Sedan',
    image: '/images/fleet/dzire.webp',
    features: ['AC', 'Music System', 'Comfortable Seats', 'Mobile Charger'],
  },
  {
    id: 'innova',
    name: 'Toyota Innova Crysta',
    nameHindi: 'टोयोटा इनोवा क्रिस्टा',
    capacity: 6,
    luggage: 4,
    type: 'Premium SUV',
    image: '/images/fleet/innvoa-crysta.jpg',
    features: ['AC', 'Premium Music', 'Leather Seats', 'Mobile Charger', 'Extra Luggage Space'],
  },
  {
    id: 'tempo',
    name: 'Tempo Traveller',
    nameHindi: 'टेम्पो ट्रैवलर',
    capacity: 12,
    luggage: 10,
    type: 'Traveller',
    image: '/images/fleet/tempo-traveller.jpg',
    features: ['AC', 'Music System', 'Push Back Seats', 'LED TV', 'Large Luggage Space'],
  },
];

export const LOCAL_RATES = {
  ertiga: [
    { hours: 4, km: 40, price: 2000 },
    { hours: 6, km: 60, price: 2500 },
    { hours: 8, km: 80, price: 3000 },
    { hours: 10, km: 100, price: 3500 },
    { hours: 12, km: 120, price: 4000 },
  ],
  dzire: [
    { hours: 4, km: 40, price: 1000 },
    { hours: 6, km: 60, price: 1500 },
    { hours: 8, km: 80, price: 2000 },
    { hours: 10, km: 100, price: 2500 },
    { hours: 12, km: 120, price: 3000 },
  ],
};

export const OUTSTATION_RATES = [
  { vehicle: 'Ertiga', plains: { perDay: 5000, extraKm: 18 }, hills: { perDay: 6500, extraKm: 23 } },
  { vehicle: 'Dzire', plains: { perDay: 3000, extraKm: 15 }, hills: { perDay: 4000, extraKm: 18 } },
  { vehicle: 'Innova Crysta', plains: { perDay: 5500, extraKm: 20 }, hills: { perDay: 7000, extraKm: 25 } },
  { vehicle: 'Tempo Traveller', plains: { perDay: 8000, extraKm: 25 }, hills: { perDay: 10000, extraKm: 30 } },
];

export const DESTINATIONS = {
  rajasthan: [
    { name: 'Jaipur', nameHindi: 'जयपुर', distance: 280, duration: '5-6 hours', image: '/images/destinations/jaipur.webp' },
    { name: 'Udaipur', nameHindi: 'उदयपुर', distance: 660, duration: '10-11 hours', image: '/images/destinations/udaipur.webp' },
    { name: 'Jodhpur', nameHindi: 'जोधपुर', distance: 590, duration: '9-10 hours', image: '/images/destinations/jodhpur.jpeg' },
    { name: 'Jaisalmer', nameHindi: 'जैसलमेर', distance: 780, duration: '12-13 hours', image: '/images/destinations/jaisalmer.webp' },
    { name: 'Ajmer', nameHindi: 'अजमेर', distance: 400, duration: '6-7 hours', image: '/images/destinations/ajmer.jpg' },
    { name: 'Pushkar', nameHindi: 'पुष्कर', distance: 415, duration: '7-8 hours', image: '/images/destinations/pushkar.jpg' },
    { name: 'Mount Abu', nameHindi: 'माउंट आबू', distance: 750, duration: '11-12 hours', image: '/images/destinations/MountAbu.jpg' },
    { name: 'Bikaner', nameHindi: 'बीकानेर', distance: 465, duration: '7-8 hours', image: '/images/destinations/bikaner.jpeg' },
  ],
  himachal: [
    { name: 'Shimla', nameHindi: 'शिमला', distance: 350, duration: '7-8 hours', image: '/images/destinations/shimla1.jpg' },
    { name: 'Manali', nameHindi: 'मनाली', distance: 540, duration: '11-12 hours', image: '/images/destinations/manali1.webp' },
    { name: 'Dharamshala', nameHindi: 'धर्मशाला', distance: 480, duration: '9-10 hours', image: '/images/destinations/dharamshala.jpg' },
    { name: 'Dalhousie', nameHindi: 'डलहौजी', distance: 560, duration: '10-11 hours', image: '/images/destinations/Dalhousie.webp' },
    { name: 'Kasol', nameHindi: 'कसोल', distance: 520, duration: '10-11 hours', image: '/images/destinations/kasol.jpg' },
    { name: 'Kullu', nameHindi: 'कुल्लू', distance: 510, duration: '10-11 hours', image: '/images/destinations/kulu-manali.jpg' },
    { name: 'Chamba', nameHindi: 'चंबा', distance: 580, duration: '11-12 hours', image: '/images/destinations/chamba.jpeg' },
  ],
  uttarakhand: [
    { name: 'Haridwar', nameHindi: 'हरिद्वार', distance: 210, duration: '4-5 hours', image: '/images/destinations/haridwar.webp' },
    { name: 'Rishikesh', nameHindi: 'ऋषिकेश', distance: 230, duration: '5-6 hours', image: '/images/destinations/rishikesh.webp' },
    { name: 'Dehradun', nameHindi: 'देहरादून', distance: 250, duration: '5-6 hours', image: '/images/destinations/Dehradun.webp' },
    { name: 'Mussoorie', nameHindi: 'मसूरी', distance: 280, duration: '6-7 hours', image: '/images/destinations/mussoorie.webp' },
    { name: 'Nainital', nameHindi: 'नैनीताल', distance: 300, duration: '6-7 hours', image: '/images/destinations/nainital.webp' },
    { name: 'Kainchi Dham', nameHindi: 'कैंची धाम', distance: 320, duration: '7-8 hours', image: '/images/destinations/kainchi-dham.webp' },
  ],
  up: [
    { name: 'Agra', nameHindi: 'आगरा', distance: 230, duration: '3-4 hours', image: '/images/destinations/agra.jpeg' },
    { name: 'Mathura', nameHindi: 'मथुरा', distance: 180, duration: '3-4 hours', image: '/images/destinations/mathura.webp' },
    { name: 'Vrindavan', nameHindi: 'वृंदावन', distance: 185, duration: '3-4 hours', image: '/images/destinations/mathura-vrindawan.avif' },
    { name: 'Lucknow', nameHindi: 'लखनऊ', distance: 555, duration: '8-9 hours', image: '/images/destinations/lucknow1.jpeg' },
    { name: 'Varanasi', nameHindi: 'वाराणसी', distance: 820, duration: '12-13 hours', image: '/images/destinations/varanasi1.jpeg' },
  ],
  punjab: [
    { name: 'Amritsar', nameHindi: 'अमृतसर', distance: 450, duration: '7-8 hours', image: '/images/destinations/amritsar.webp' },
    { name: 'Chandigarh', nameHindi: 'चंडीगढ़', distance: 250, duration: '4-5 hours', image: '/images/destinations/chandigarh1.jpeg' },
    { name: 'Ludhiana', nameHindi: 'लुधियाना', distance: 310, duration: '5-6 hours', image: '/images/destinations/ludhiana.jpeg' },
    { name: 'Patiala', nameHindi: 'पटियाला', distance: 270, duration: '4-5 hours', image: '/images/destinations/patiala.jpeg' },
  ],
};

export const SERVICES = [
  {
    id: 'airport',
    icon: 'Plane',
    image: '/images/services/airport-transfer.jpg',
    title: 'Airport Transfer',
    titleHindi: 'एयरपोर्ट ट्रांसफर',
    description: 'Pickup and drop services to/from Delhi IGI Airport with flight tracking and meet-and-greet',
    descriptionHindi: 'फ्लाइट ट्रैकिंग और मीट-एंड-ग्रीट के साथ दिल्ली IGI एयरपोर्ट से पिकअप और ड्रॉप सेवाएं',
    features: ['Flight Tracking', 'Meet & Greet', '24/7 Service', 'Fixed Rates'],
  },
  {
    id: 'local',
    icon: 'MapPin',
    image: '/images/services/hourly-rental.jpg',
    title: 'City Rides',
    titleHindi: 'शहर की सवारी',
    description: 'Rides within Delhi NCR for shopping, meetings, and sightseeing with hourly packages',
    descriptionHindi: 'खरीदारी, मीटिंग और दर्शनीय स्थलों के लिए दिल्ली एनसीआर में प्रति घंटा पैकेज के साथ सवारी',
    features: ['Hourly Packages', 'Point to Point', 'Flexible Timing', 'AC Cabs'],
  },
  {
    id: 'corporate',
    icon: 'Briefcase',
    image: '/images/services/coroporate-services.jpg',
    title: 'Corporate Travel',
    titleHindi: 'कॉर्पोरेट यात्रा',
    description: 'Professional transportation for businesses, employee commute, and client pickups',
    descriptionHindi: 'व्यवसायों, कर्मचारी आवागमन और ग्राहक पिकअप के लिए पेशेवर परिवहन',
    features: ['Monthly Billing', 'Dedicated Drivers', 'Corporate Rates', 'Punctual Service'],
  },
  {
    id: 'sightseeing',
    icon: 'Camera',
    image: '/images/services/local-packages.jpg',
    title: 'Sightseeing Tours',
    titleHindi: 'दर्शनीय स्थल यात्रा',
    description: "Guided tours of Delhi's monuments, temples, and attractions",
    descriptionHindi: 'दिल्ली के स्मारकों, मंदिरों और आकर्षणों की गाइडेड यात्राएं',
    features: ['Delhi Darshan', 'Full Day Tours', 'Experienced Guides', 'Photo Stops'],
  },
  {
    id: 'wedding',
    icon: 'Heart',
    image: '/images/services/wedding-and-events.webp',
    title: 'Wedding Transportation',
    titleHindi: 'शादी परिवहन',
    description: 'Decorated vehicles for weddings, baraat, and guest transportation',
    descriptionHindi: 'शादी, बारात और मेहमानों के परिवहन के लिए सजी हुई गाड़ियां',
    features: ['Decorated Vehicles', 'Baraat Service', 'Guest Pickup', 'Premium Cars'],
  },
  {
    id: 'outstation',
    icon: 'Route',
    image: '/images/services/outstation-tips.jpg',
    title: 'Outstation Trips',
    titleHindi: 'आउटस्टेशन यात्राएं',
    description: 'One-way and round trips to popular destinations across India',
    descriptionHindi: 'भारत भर के लोकप्रिय गंतव्यों के लिए एकतरफा और राउंड ट्रिप',
    features: ['One-Way Available', 'Round Trips', 'Pan India', 'Flexible Itinerary'],
  },
  {
    id: 'pilgrimage',
    icon: 'Mountain',
    image: '/images/services/travel-char-dham-yatra.webp',
    title: 'Pilgrimage Tours',
    titleHindi: 'तीर्थ यात्राएं',
    description: 'Char Dham Yatra and other sacred destination tours with experienced drivers',
    descriptionHindi: 'अनुभवी ड्राइवरों के साथ चार धाम यात्रा और अन्य पवित्र स्थलों की यात्राएं',
    features: ['Char Dham Yatra', 'Religious Tours', 'Experienced Drivers', 'Comfortable Journey'],
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    nameHindi: 'राजेश कुमार',
    location: 'Noida',
    rating: 5,
    text: 'Excellent service! The driver was punctual and very professional. The car was clean and comfortable. Highly recommend for airport transfers.',
    textHindi: 'उत्कृष्ट सेवा! ड्राइवर समय पर था और बहुत पेशेवर था। कार साफ और आरामदायक थी। एयरपोर्ट ट्रांसफर के लिए अत्यधिक अनुशंसित।',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    nameHindi: 'प्रिया शर्मा',
    location: 'Gurgaon',
    rating: 5,
    text: 'We booked for our family trip to Jaipur. The Innova was in great condition and the driver was very knowledgeable about the route. Will book again!',
    textHindi: 'हमने जयपुर की पारिवारिक यात्रा के लिए बुक किया। इनोवा बहुत अच्छी स्थिति में थी और ड्राइवर मार्ग के बारे में बहुत जानकार था। फिर से बुक करेंगे!',
  },
  {
    id: 3,
    name: 'Amit Verma',
    nameHindi: 'अमित वर्मा',
    location: 'Delhi',
    rating: 5,
    text: 'Been using Shree Ji for corporate travel for 2 years now. Reliable, professional, and always on time. Best taxi service in Delhi NCR.',
    textHindi: 'पिछले 2 साल से कॉर्पोरेट यात्रा के लिए श्री जी का उपयोग कर रहा हूं। विश्वसनीय, पेशेवर और हमेशा समय पर। दिल्ली एनसीआर में सबसे अच्छी टैक्सी सेवा।',
  },
  {
    id: 4,
    name: 'Sunita Devi',
    nameHindi: 'सुनीता देवी',
    location: 'Faridabad',
    rating: 5,
    text: 'Booked Tempo Traveller for Char Dham Yatra. The driver was experienced with hill routes and very caring. A memorable pilgrimage experience.',
    textHindi: 'चार धाम यात्रा के लिए टेम्पो ट्रैवलर बुक किया। ड्राइवर पहाड़ी मार्गों में अनुभवी और बहुत देखभाल करने वाला था। एक यादगार तीर्थ यात्रा अनुभव।',
  },
];

export const FAQ_DATA = [
  {
    question: 'What are your payment options?',
    questionHindi: 'आपके भुगतान विकल्प क्या हैं?',
    answer: 'We accept cash, UPI (Google Pay, PhonePe, Paytm), and bank transfers. Payment is typically made at the end of the trip.',
    answerHindi: 'हम नकद, UPI (Google Pay, PhonePe, Paytm) और बैंक ट्रांसफर स्वीकार करते हैं। भुगतान आमतौर पर यात्रा के अंत में किया जाता है।',
  },
  {
    question: 'How do I book a taxi?',
    questionHindi: 'मैं टैक्सी कैसे बुक करूं?',
    answer: 'You can book via WhatsApp, phone call, or through the booking form on our website. We recommend booking at least 2-3 hours in advance for local rides and 1 day in advance for outstation trips.',
    answerHindi: 'आप व्हाट्सएप, फोन कॉल या हमारी वेबसाइट पर बुकिंग फॉर्म के माध्यम से बुक कर सकते हैं। हम लोकल राइड के लिए कम से कम 2-3 घंटे पहले और आउटस्टेशन ट्रिप के लिए 1 दिन पहले बुकिंग की सलाह देते हैं।',
  },
  {
    question: 'Are toll and parking charges included?',
    questionHindi: 'क्या टोल और पार्किंग शुल्क शामिल हैं?',
    answer: 'No, toll charges, parking fees, and state entry taxes are extra and payable by the customer during the journey.',
    answerHindi: 'नहीं, टोल शुल्क, पार्किंग शुल्क और राज्य प्रवेश कर अतिरिक्त हैं और यात्रा के दौरान ग्राहक द्वारा देय हैं।',
  },
  {
    question: 'What is driver allowance (DA)?',
    questionHindi: 'ड्राइवर भत्ता (DA) क्या है?',
    answer: 'For outstation trips, driver allowance of Rs. 300-500 per night is charged separately to cover driver accommodation and food expenses.',
    answerHindi: 'आउटस्टेशन यात्राओं के लिए, ड्राइवर आवास और भोजन खर्च को कवर करने के लिए रु. 300-500 प्रति रात का ड्राइवर भत्ता अलग से लिया जाता है।',
  },
  {
    question: 'Can I modify or cancel my booking?',
    questionHindi: 'क्या मैं अपनी बुकिंग में बदलाव या रद्द कर सकता हूं?',
    answer: 'Yes, you can modify or cancel your booking by contacting us. We request at least 4 hours notice for cancellations to avoid charges.',
    answerHindi: 'हां, आप हमसे संपर्क करके अपनी बुकिंग में बदलाव या रद्द कर सकते हैं। शुल्क से बचने के लिए हम रद्दीकरण के लिए कम से कम 4 घंटे पहले सूचना का अनुरोध करते हैं।',
  },
  {
    question: 'Do you provide child seats?',
    questionHindi: 'क्या आप चाइल्ड सीट प्रदान करते हैं?',
    answer: 'Yes, we can arrange child seats on request. Please mention this requirement while booking.',
    answerHindi: 'हां, हम अनुरोध पर चाइल्ड सीट की व्यवस्था कर सकते हैं। कृपया बुकिंग करते समय इस आवश्यकता का उल्लेख करें।',
  },
];
